# Generated by Django 3.2.20 on 2023-08-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0003_auto_20230831_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ab',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='avg',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bb',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cs',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='dp',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fc',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gp',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gs',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='h',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hbp',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hr',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ibb',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='k',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lob',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='obp',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ops',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pa',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='r',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rbi',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='roe',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sb',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sf',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sh',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='slg',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='tb',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='threeb',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='twob',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
