# Generated by Django 3.2.20 on 2023-09-01 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0005_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date_played',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team',
        ),
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(max_length=10),
        ),
    ]
