# Generated by Django 3.2.20 on 2023-10-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0007_auto_20230901_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ab',
        ),
        migrations.RemoveField(
            model_name='player',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='h',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hbp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ibb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='k',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lob',
        ),
        migrations.RemoveField(
            model_name='player',
            name='obp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ops',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pa',
        ),
        migrations.RemoveField(
            model_name='player',
            name='r',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rbi',
        ),
        migrations.RemoveField(
            model_name='player',
            name='roe',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sf',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sh',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slg',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='threeb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='twob',
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.DecimalField(decimal_places=3, default='0.000', max_digits=4)),
                ('gp', models.PositiveIntegerField(default='0')),
                ('gs', models.PositiveIntegerField(default='0')),
                ('pa', models.PositiveIntegerField(default='0')),
                ('ab', models.PositiveIntegerField(default='0')),
                ('r', models.PositiveIntegerField(default='0')),
                ('h', models.PositiveIntegerField(default='0')),
                ('twob', models.PositiveIntegerField(default='0')),
                ('threeb', models.PositiveIntegerField(default='0')),
                ('hr', models.PositiveIntegerField(default='0')),
                ('rbi', models.PositiveIntegerField(default='0')),
                ('bb', models.PositiveIntegerField(default='0')),
                ('k', models.PositiveIntegerField(default='0')),
                ('hbp', models.PositiveIntegerField(default='0')),
                ('ibb', models.PositiveIntegerField(default='0')),
                ('sb', models.PositiveIntegerField(default='0')),
                ('cs', models.PositiveIntegerField(default='0')),
                ('sh', models.PositiveIntegerField(default='0')),
                ('sf', models.PositiveIntegerField(default='0')),
                ('dp', models.PositiveIntegerField(default='0')),
                ('roe', models.PositiveIntegerField(default='0')),
                ('fc', models.PositiveIntegerField(default='0')),
                ('lob', models.PositiveIntegerField(default='0')),
                ('tb', models.PositiveIntegerField(default='0')),
                ('obp', models.DecimalField(decimal_places=3, default='0.000', max_digits=4)),
                ('slg', models.DecimalField(decimal_places=3, default='0.000', max_digits=4)),
                ('ops', models.DecimalField(decimal_places=3, default='0.000', max_digits=4)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.player')),
            ],
        ),
    ]
